<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Windows.CsWin32" PrivateAssets="all" />
    <ProjectReference Include="..\GpuPreferenceManager.Core\GpuPreferenceManager.Core.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Vortice.DXGI" />
  </ItemGroup>
</Project>
