<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\GpuPreferenceManager.Core\GpuPreferenceManager.Core.csproj" />
    <ProjectReference Include="..\..\src\GpuPreferenceManager.Windows\GpuPreferenceManager.Windows.csproj" />
  </ItemGroup>
</Project>
